require_cut "active_record"
require_cut "rack"
require_cut "div"
require_cut "dials"
require_cut "logger"

require "./lib/config/environment"
require "./lib/views/.cache/home.html"
require "./lib/views/.cache/login_form.html"
require "./lib/views/.cache/projects_table.html"
require "./lib/views/.cache/project_show.html"
require "./lib/views/.cache/project_form.html"
require "./lib/views/.cache/task_form.html"
require "./lib/views/.cache/layout.html"

require "./lib/helpers/logging"
require "./lib/database"
require "./lib/models/user"
require "./lib/models/session"
require "./lib/models/project"
require "./lib/models/task"
require "./lib/helpers/auth"
require "./lib/controllers/sessions_controller"
require "./lib/controllers/projects_controller"
require "./lib/controllers/tasks_controller"
require "./lib/routes"
require "./lib/middleware"
