require "../../lib/minitest"
require "../../packages/arel/arel"

def run_tests()
  def test_core_expressions_have_deterministic_inspection()
    people = Arel.table("people")
    arithmetic = people.column("score").add_expression(Arel.literal(2))
    cast = Arel.cast(arithmetic, "TEXT")
    function = Arel.function("LOWER", [cast])
    Minitest.assert_equal("Attribute(people.score)", Arel.inspect(people.column("score")))
    Minitest.assert_equal("Binary(+, Attribute(people.score), Literal(2))", Arel.inspect(arithmetic))
    Minitest.assert_equal("Function(LOWER, [Cast(Binary(+, Attribute(people.score), Literal(2)), TEXT)])", Arel.inspect(function))
    Minitest.assert_equal("Excluded(qty)", Arel.inspect(Arel.excluded("qty")))
    Minitest.assert_equal("Table(people)", Arel.inspect(people))
    Minitest.assert_equal("Table(people AS p)", Arel.inspect(people.as("p")))
    Minitest.assert_equal("QualifiedStar(people)", Arel.inspect(people.star()))
    Minitest.assert_equal("ConflictAttribute(code)", Arel.inspect(Arel.conflict_target([]).column("code")))
    subquery = Arel.from(people).project(people.column("id"))
    Minitest.assert_equal("Exists(Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(Arel.exists(subquery)))
    Minitest.assert_equal("NotExists(Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(Arel.not_exists(subquery)))
    Minitest.assert_equal("Scalar(Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(Arel.scalar(subquery)))
    roles = Arel.table("roles")
    join = ArelJoin.new(roles, people.column("role_id").eq(roles.column("id")), "LEFT OUTER")
    Minitest.assert_equal("Join(LEFT OUTER, Table(roles), Predicate(=, Attribute(people.role_id), Attribute(roles.id)))", Arel.inspect(join))
    predicate = people.column("active").eq(Arel.literal(true))
    combined = predicate.and_also(people.column("score").gt(10)).not_()
    Minitest.assert_equal("Predicate(=, Attribute(people.active), Literal(true))", Arel.inspect(predicate))
    Minitest.assert_equal("Not(Logical(AND, Predicate(=, Attribute(people.active), Literal(true)), Predicate(>, Attribute(people.score), Bind(10))))", Arel.inspect(combined))
    Minitest.assert_equal("Between(BETWEEN, Attribute(people.age), 18, 65)", Arel.inspect(people.column("age").between(18, 65)))
    Minitest.assert_equal("Membership(NOT IN, Attribute(people.role), 2 values)", Arel.inspect(people.column("role").not_in(["guest", "blocked"])))
    ordering = Arel.asc(people.column("name").collate("nocase")).nulls_last()
    aliased = Arel.as(ordering, "ordered_name")
    Minitest.assert_equal("Alias(ordered_name, Ordering(ASC, NULLS LAST, Collation(nocase, Attribute(people.name))))", Arel.inspect(aliased))
    query = Arel.from(people).project([people.column("name"), people.column("age")])
    query = query.where(people.column("active").eq(true))
    Minitest.assert_equal("Query(from=people, projections=2, predicates=1, joins=0, ctes=0)", Arel.inspect(query))
    first = people.column("score").add_expression(Arel.literal(2))
    second = Arel.table("people").column("score").add_expression(Arel.literal(2))
    different = people.column("score").add_expression(Arel.literal(3))
    Minitest.assert_equal(true, Arel.same?(first, second))
    Minitest.assert_equal(false, Arel.same?(first, different))
    first_predicate = people.column("active").eq(true).and_also(people.column("age").gt(18))
    same_predicate = Arel.table("people").column("active").eq(true)
    same_predicate = same_predicate.and_also(Arel.table("people").column("age").gt(18))
    other_predicate = people.column("active").eq(false).and_also(people.column("age").gt(18))
    Minitest.assert_equal(true, Arel.same?(first_predicate, same_predicate))
    Minitest.assert_equal(false, Arel.same?(first_predicate, other_predicate))
    first_ordering = Arel.asc(people.column("name").collate("nocase")).nulls_last()
    same_ordering = Arel.asc(Arel.table("people").column("name").collate("nocase"))
    same_ordering = same_ordering.nulls_last()
    other_ordering = Arel.desc(people.column("name").collate("nocase")).nulls_last()
    Minitest.assert_equal(true, Arel.same?(first_ordering, same_ordering))
    Minitest.assert_equal(false, Arel.same?(first_ordering, other_ordering))
    first_query = Arel.from(people).project(people.column("name"))
    first_query = first_query.where(people.column("active").eq(true)).order(first_ordering)
    same_people = Arel.table("people")
    same_query = Arel.from(same_people).project(same_people.column("name"))
    same_query = same_query.where(same_people.column("active").eq(true))
    same_query = same_query.order(Arel.asc(same_people.column("name").collate("nocase")).nulls_last())
    other_query = same_query.take(1)
    Minitest.assert_equal(true, Arel.same?(first_query, same_query))
    Minitest.assert_equal(false, Arel.same?(first_query, other_query))
  end

  suite = Minitest.new()
  suite.test("core expression inspection", test_core_expressions_have_deterministic_inspection)
  suite.run()
end

run_tests()
