require "../../lib/minitest"
require "../../packages/arel/arel"

def run_tests()
  def test_core_expressions_have_deterministic_inspection()
    people = Arel.table("people")
    arithmetic = people.column("score").add_expression(Arel.literal(2))
    cast = Arel.cast(arithmetic, "TEXT")
    function = Arel.function("LOWER", [cast])
    Minitest.assert_equal("Attribute(people.score)", Arel.inspect(people.column("score")))
    Minitest.assert_equal("Binary(+, Attribute(people.score), Literal(2))", Arel.inspect(arithmetic))
    Minitest.assert_equal("Function(LOWER, [Cast(Binary(+, Attribute(people.score), Literal(2)), TEXT)])", Arel.inspect(function))
    Minitest.assert_equal("Excluded(qty)", Arel.inspect(Arel.excluded("qty")))
    Minitest.assert_equal("Table(people)", Arel.inspect(people))
    Minitest.assert_equal("Table(people AS p)", Arel.inspect(people.as("p")))
    Minitest.assert_equal("QualifiedStar(people)", Arel.inspect(people.star()))
    Minitest.assert_equal("ConflictAttribute(code)", Arel.inspect(Arel.conflict_target([]).column("code")))
    subquery = Arel.from(people).project(people.column("id"))
    Minitest.assert_equal("Exists(Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(Arel.exists(subquery)))
    Minitest.assert_equal("NotExists(Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(Arel.not_exists(subquery)))
    Minitest.assert_equal("Scalar(Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(Arel.scalar(subquery)))
    Minitest.assert_equal("Assignment(Attribute(people.score))", Arel.inspect(Arel.expression(people.column("score"))))
    Minitest.assert_equal("ConflictTarget(email, tenant_id, predicate=false)", Arel.inspect(Arel.conflict_target(["email", "tenant_id"])))
    Minitest.assert_equal("DefaultValues", Arel.inspect(ArelDefaultValues.new()))
    roles = Arel.table("roles")
    join = ArelJoin.new(roles, people.column("role_id").eq(roles.column("id")), "LEFT OUTER")
    Minitest.assert_equal("Join(LEFT OUTER, Table(roles), Predicate(=, Attribute(people.role_id), Attribute(roles.id)))", Arel.inspect(join))
    Minitest.assert_equal("Cte(active_people, ordinary, Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(ArelCte.new("active_people", subquery)))
    Minitest.assert_equal("Cte(tree, recursive, Query(from=people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(ArelCte.new("tree", subquery, true)))
    archived = Arel.from(Arel.table("archived_people")).project(Arel.table("archived_people").column("id"))
    compound = Arel.union(subquery, archived)
    Minitest.assert_equal("Compound(UNION, Query(from=people, projections=1, predicates=0, joins=0, ctes=0), Query(from=archived_people, projections=1, predicates=0, joins=0, ctes=0))", Arel.inspect(compound))
    predicate = people.column("active").eq(Arel.literal(true))
    combined = predicate.and_also(people.column("score").gt(10)).not_()
    Minitest.assert_equal("Predicate(=, Attribute(people.active), Literal(true))", Arel.inspect(predicate))
    Minitest.assert_equal("Not(Logical(AND, Predicate(=, Attribute(people.active), Literal(true)), Predicate(>, Attribute(people.score), Bind(10))))", Arel.inspect(combined))
    Minitest.assert_equal("Between(BETWEEN, Attribute(people.age), 18, 65)", Arel.inspect(people.column("age").between(18, 65)))
    Minitest.assert_equal("Membership(NOT IN, Attribute(people.role), 2 values)", Arel.inspect(people.column("role").not_in(["guest", "blocked"])))
    ordering = Arel.asc(people.column("name").collate("nocase")).nulls_last()
    aliased = Arel.as(ordering, "ordered_name")
    Minitest.assert_equal("Alias(ordered_name, Ordering(ASC, NULLS LAST, Collation(nocase, Attribute(people.name))))", Arel.inspect(aliased))
    query = Arel.from(people).project([people.column("name"), people.column("age")])
    query = query.where(people.column("active").eq(true))
    Minitest.assert_equal("Query(from=people, projections=2, predicates=1, joins=0, ctes=0)", Arel.inspect(query))
  end

  def test_nodes_compare_structurally()
    people = Arel.table("people")
    subquery = Arel.from(people).project(people.column("id"))
    first = people.column("score").add_expression(Arel.literal(2))
    second = Arel.table("people").column("score").add_expression(Arel.literal(2))
    different = people.column("score").add_expression(Arel.literal(3))
    Minitest.assert_equal(true, Arel.same?(first, second))
    Minitest.assert_equal(false, Arel.same?(first, different))
    Minitest.assert_equal(true, Arel.same?(Arel.function("COALESCE", [people.column("name"), Arel.literal(0)]), Arel.function("COALESCE", [Arel.table("people").column("name"), Arel.literal(0)])))
    Minitest.assert_equal(false, Arel.same?(Arel.count(people.column("id")), Arel.count_distinct(people.column("id"))))
    Minitest.assert_equal(true, Arel.same?(Arel.sql("score > ?", [10]), Arel.sql("score > ?", [10])))
    Minitest.assert_equal(false, Arel.same?(Arel.sql("score > ?", [10]), Arel.sql("score > ?", [11])))
    Minitest.assert_equal(true, Arel.same?(Arel.expression(people.column("score")), Arel.expression(Arel.table("people").column("score"))))
    Minitest.assert_equal(true, Arel.same?(ArelDefaultValues.new(), ArelDefaultValues.new()))
    first_target = Arel.conflict_target(["email"]).where(people.column("active").eq(Arel.literal(true)))
    same_target = Arel.conflict_target(["email"]).where(Arel.table("people").column("active").eq(Arel.literal(true)))
    Minitest.assert_equal(true, Arel.same?(first_target, same_target))
    Minitest.assert_equal(false, Arel.same?(first_target, Arel.conflict_target(["username"])))
    Minitest.assert_equal(true, Arel.same?(people.column("role").in_list(["admin", "staff"]), Arel.table("people").column("role").in_list(["admin", "staff"])))
    Minitest.assert_equal(false, Arel.same?(people.column("role").in_list(["admin"]), people.column("role").in_list(["staff"])))
    Minitest.assert_equal(true, Arel.same?(people.column("id").in_subquery(subquery), Arel.table("people").column("id").in_subquery(Arel.from(Arel.table("people")).project(Arel.table("people").column("id")))))
    first_predicate = people.column("active").eq(true).and_also(people.column("age").gt(18))
    same_predicate = Arel.table("people").column("active").eq(true)
    same_predicate = same_predicate.and_also(Arel.table("people").column("age").gt(18))
    other_predicate = people.column("active").eq(false).and_also(people.column("age").gt(18))
    Minitest.assert_equal(true, Arel.same?(first_predicate, same_predicate))
    Minitest.assert_equal(false, Arel.same?(first_predicate, other_predicate))
    first_ordering = Arel.asc(people.column("name").collate("nocase")).nulls_last()
    same_ordering = Arel.asc(Arel.table("people").column("name").collate("nocase"))
    same_ordering = same_ordering.nulls_last()
    other_ordering = Arel.desc(people.column("name").collate("nocase")).nulls_last()
    Minitest.assert_equal(true, Arel.same?(first_ordering, same_ordering))
    Minitest.assert_equal(false, Arel.same?(first_ordering, other_ordering))
    first_query = Arel.from(people).project(people.column("name"))
    first_query = first_query.where(people.column("active").eq(true)).order(first_ordering)
    same_people = Arel.table("people")
    same_query = Arel.from(same_people).project(same_people.column("name"))
    same_query = same_query.where(same_people.column("active").eq(true))
    same_query = same_query.order(Arel.asc(same_people.column("name").collate("nocase")).nulls_last())
    other_query = same_query.take(1)
    Minitest.assert_equal(true, Arel.same?(first_query, same_query))
    Minitest.assert_equal(false, Arel.same?(first_query, other_query))
  end

  def test_queries_compare_structurally()
    people = Arel.table("people")
    subquery = Arel.from(people).project(people.column("id"))
    grouped = Arel.from(people).project(people.column("role")).group(people.column("role"))
    grouped = grouped.having(Arel.count(people.column("id")).gt(1))
    same_grouped = Arel.from(Arel.table("people")).project(Arel.table("people").column("role"))
    same_grouped = same_grouped.group(Arel.table("people").column("role"))
    same_grouped = same_grouped.having(Arel.count(Arel.table("people").column("id")).gt(1))
    Minitest.assert_equal(true, Arel.same?(grouped, same_grouped))
    Minitest.assert_equal(false, Arel.same?(grouped, same_grouped.having(people.column("active").eq(true))))
    roles = Arel.table("roles")
    joined = Arel.from(people).join(roles, people.column("role_id").eq(roles.column("id")))
    same_roles = Arel.table("roles")
    same_joined = Arel.from(Arel.table("people")).join(same_roles,
      Arel.table("people").column("role_id").eq(same_roles.column("id")))
    Minitest.assert_equal(true, Arel.same?(joined, same_joined))
    Minitest.assert_equal(false, Arel.same?(joined, Arel.from(people).left_join(roles,
      people.column("role_id").eq(roles.column("id")))))
    derived = Arel.from_subquery(subquery, "selected_people")
    same_derived = Arel.from_subquery(Arel.from(Arel.table("people")).project(
      Arel.table("people").column("id")), "selected_people")
    other_derived = Arel.from_subquery(Arel.from(Arel.table("people")).project(
      Arel.table("people").column("name")), "selected_people")
    Minitest.assert_equal(true, Arel.same?(derived, same_derived))
    Minitest.assert_equal(false, Arel.same?(derived, other_derived))
    with_cte = Arel.from(people).with("selected", subquery)
    same_with_cte = Arel.from(Arel.table("people")).with("selected",
      Arel.from(Arel.table("people")).project(Arel.table("people").column("id")))
    Minitest.assert_equal(true, Arel.same?(with_cte, same_with_cte))
    Minitest.assert_equal(false, Arel.same?(with_cte, Arel.from(people).with_recursive("selected", subquery)))
    archived = Arel.from(Arel.table("archived_people")).project(Arel.table("archived_people").column("id"))
    compound = Arel.union(subquery, archived).order(people.column("id").asc()).take(5)
    same_compound = Arel.union(Arel.from(Arel.table("people")).project(
      Arel.table("people").column("id")), archived).order(
      Arel.table("people").column("id").asc()).take(5)
    Minitest.assert_equal(true, Arel.same?(compound, same_compound))
    Minitest.assert_equal(false, Arel.same?(compound, Arel.union_all(subquery, archived).take(5)))
  end

  def test_write_managers_have_structural_tooling()
    people = Arel.table("people")
    insert = Arel.insert_into(people).values({"name": "Ada"}).returning(people.column("id"))
    Minitest.assert_equal("Insert(into=people, rows=1, source=false, returning=1, ctes=0)", Arel.inspect(insert))
    update = Arel.update(people).set({"active": true}).where(people.column("id").eq(1))
    Minitest.assert_equal("Update(table=people, assignments=1, predicates=1, returning=0, all=false, ctes=0)", Arel.inspect(update))
  end

  suite = Minitest.new()
  suite.test("core expression inspection", test_core_expressions_have_deterministic_inspection)
  suite.test("structural equality", test_nodes_compare_structurally)
  suite.test("query structural equality", test_queries_compare_structurally)
  suite.test("write manager structural tooling", test_write_managers_have_structural_tooling)
  suite.run()
end

run_tests()
