b = ProgramBuilder.new()
fn = b.declare_function("double", 1, 1)
b.emit_byte(fn, 6)
b.emit_byte(fn, 1)
b.emit_byte(fn, 0)
b.emit_byte(fn, 0)
b.emit_byte(fn, 57)
b.emit_byte(fn, 1)
b.set_register_count(fn, 2)

c = b.add_constant(-1, 5)
b.emit_byte(-1, 0)
b.emit_byte(-1, 0)
b.emit_byte(-1, c)
b.emit_byte(-1, 29)
b.emit_byte(-1, 1)
b.emit_byte(-1, 0)
b.emit_byte(-1, fn)
b.emit_byte(-1, 0)
b.emit_byte(-1, 1)
b.emit_byte(-1, 57)
b.emit_byte(-1, 1)
b.set_register_count(-1, 2)

b.run()
